package bg.tusofia.fksu.soa.examples.corba.server;

import bg.tusofia.fksu.soa.examples.corba.Hello;
import bg.tusofia.fksu.soa.examples.corba.HelloHelper;
import bg.tusofia.fksu.soa.examples.corba.HelloOperations;

/**
 * HelloApp/HelloPOA.java . Generated by the IDL-to-Java compiler (portable),
 * version "3.2" from C:/Hello.idl Thursday, October 17, 2013 1:12:54 AM EEST
 */

public abstract class HelloPOA extends org.omg.PortableServer.Servant
		implements HelloOperations, org.omg.CORBA.portable.InvokeHandler {

	// Constructors

	private static java.util.Hashtable<String, Integer> _methods = new java.util.Hashtable<String, Integer>();

	static {
		_methods.put("sayHello", new java.lang.Integer(0));
		_methods.put("shutdown", new java.lang.Integer(1));
	}

	public org.omg.CORBA.portable.OutputStream _invoke(String $method, org.omg.CORBA.portable.InputStream in,
			org.omg.CORBA.portable.ResponseHandler $rh) {
		org.omg.CORBA.portable.OutputStream out = null;
		java.lang.Integer __method = (java.lang.Integer) _methods.get($method);
		if (__method == null)
			throw new org.omg.CORBA.BAD_OPERATION(0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

		switch (__method.intValue()) {
		case 0: // HelloApp/Hello/sayHello
		{
			String $result = null;
			$result = this.sayHello();
			out = $rh.createReply();
			out.write_string($result);
			break;
		}

		case 1: // HelloApp/Hello/shutdown
		{
			this.shutdown();
			out = $rh.createReply();
			break;
		}

		default:
			throw new org.omg.CORBA.BAD_OPERATION(0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
		}

		return out;
	} // _invoke

	// Type-specific CORBA::Object operations
	private static String[] __ids = { "IDL:HelloApp/Hello:1.0" };

	public String[] _all_interfaces(org.omg.PortableServer.POA poa, byte[] objectId) {
		return (String[]) __ids.clone();
	}

	public Hello _this() {
		return HelloHelper.narrow(super._this_object());
	}

	public Hello _this(org.omg.CORBA.ORB orb) {
		return HelloHelper.narrow(super._this_object(orb));
	}

} // class HelloPOA
