//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2013.10.10 at 01:11:15 PM EEST
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://opa/default", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package bg.tusofia.cst.ds.xml.jaxb;
