//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.10 at 01:11:15 PM EEST 
//

package bg.tusofia.fksu.soa.examples.xml.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;

/**
 * <p>
 * Java class for MovieType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="MovieType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="length">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>short">
 *                 &lt;attribute name="unit" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="synopsis" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *       &lt;attribute name="rating" type="{http://www.w3.org/2001/XMLSchema}float" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MovieType", namespace = "http://opa/cool", propOrder = { "title", "length", "synopsis" })
public class MovieType {

	@XmlElement(required = true)
	protected String title;
	@XmlElement(required = true)
	protected MovieType.Length length;
	@XmlElement(required = true)
	protected String synopsis;
	@XmlAttribute(name = "rating")
	protected Float rating;

	/**
	 * Gets the value of the title property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * Sets the value of the title property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setTitle(String value) {
		this.title = value;
	}

	/**
	 * Gets the value of the length property.
	 * 
	 * @return possible object is {@link MovieType.Length }
	 * 
	 */
	public MovieType.Length getLength() {
		return length;
	}

	/**
	 * Sets the value of the length property.
	 * 
	 * @param value
	 *            allowed object is {@link MovieType.Length }
	 * 
	 */
	public void setLength(MovieType.Length value) {
		this.length = value;
	}

	/**
	 * Gets the value of the synopsis property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getSynopsis() {
		return synopsis;
	}

	/**
	 * Sets the value of the synopsis property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setSynopsis(String value) {
		this.synopsis = value;
	}

	/**
	 * Gets the value of the rating property.
	 * 
	 * @return possible object is {@link Float }
	 * 
	 */
	public Float getRating() {
		return rating;
	}

	/**
	 * Sets the value of the rating property.
	 * 
	 * @param value
	 *            allowed object is {@link Float }
	 * 
	 */
	public void setRating(Float value) {
		this.rating = value;
	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained
	 * within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;simpleContent>
	 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>short">
	 *       &lt;attribute name="unit" type="{http://www.w3.org/2001/XMLSchema}string" />
	 *     &lt;/extension>
	 *   &lt;/simpleContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "value" })
	public static class Length {

		@XmlValue
		protected short value;
		@XmlAttribute(name = "unit")
		protected String unit;

		/**
		 * Gets the value of the value property.
		 * 
		 */
		public short getValue() {
			return value;
		}

		/**
		 * Sets the value of the value property.
		 * 
		 */
		public void setValue(short value) {
			this.value = value;
		}

		/**
		 * Gets the value of the unit property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getUnit() {
			return unit;
		}

		/**
		 * Sets the value of the unit property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setUnit(String value) {
			this.unit = value;
		}

	}

}
