//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.10 at 01:11:15 PM EEST 
//

package bg.tusofia.fksu.soa.examples.xml.jaxb;

import javax.xml.bind.annotation.XmlRegistry;

/**
 * This object contains factory methods for each Java content interface and Java
 * element interface generated in the bg.tusofia.fksu.soa.examples.jaxb package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the
 * Java representation for XML content. The Java representation of XML content
 * can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory
 * methods for each of these are provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

	/**
	 * Create a new ObjectFactory that can be used to create new instances of
	 * schema derived classes for package: bg.tusofia.fksu.soa.examples.jaxb
	 * 
	 */
	public ObjectFactory() {
	}

	/**
	 * Create an instance of {@link MovieType }
	 * 
	 */
	public MovieType createMovieType() {
		return new MovieType();
	}

	/**
	 * Create an instance of {@link Cinema }
	 * 
	 */
	public Cinema createCinema() {
		return new Cinema();
	}

	/**
	 * Create an instance of {@link MovieType.Length }
	 * 
	 */
	public MovieType.Length createMovieTypeLength() {
		return new MovieType.Length();
	}

}
