package bg.tusofia.fksu.soa.examples.corba;

/**
 * HelloApp/HelloHolder.java . Generated by the IDL-to-Java compiler (portable),
 * version "3.2" from C:/Hello.idl Thursday, October 17, 2013 1:11:08 AM EEST
 */

public final class HelloHolder implements org.omg.CORBA.portable.Streamable {
	public Hello value = null;

	public HelloHolder() {
	}

	public HelloHolder(Hello initialValue) {
		value = initialValue;
	}

	public void _read(org.omg.CORBA.portable.InputStream i) {
		value = HelloHelper.read(i);
	}

	public void _write(org.omg.CORBA.portable.OutputStream o) {
		HelloHelper.write(o, value);
	}

	public org.omg.CORBA.TypeCode _type() {
		return HelloHelper.type();
	}

}
