package bg.tusofia.fksu.soa.examples.corba;

/**
 * HelloApp/Hello.java . Generated by the IDL-to-Java compiler (portable),
 * version "3.2" from C:/Hello.idl Thursday, October 17, 2013 1:11:08 AM EEST
 */

public interface Hello extends HelloOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity {
} // interface Hello
