package bg.tusofia.fksu.soa.examples.corba;

/**
 * HelloApp/HelloOperations.java . Generated by the IDL-to-Java compiler
 * (portable), version "3.2" from C:/Hello.idl Thursday, October 17, 2013
 * 1:11:08 AM EEST
 */

public interface HelloOperations {
	String sayHello();

	void shutdown();
} // interface HelloOperations
